/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserPosts_viewer.graphql
 * @generated SignedSource<<35a22d89c808092a65534a321953c618>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserPosts_viewer = {|
  +user: ?{|
    +posts: ?{|
      +pageInfo: {|
        +hasNextPage: boolean;
        +endCursor: ?string;
      |};
      +edges: ?$ReadOnlyArray<?{|
        +node: ?{|
          +id: string;
        |};
      |}>;
    |};
  |};
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [
    {
      kind: 'RootArgument',
      name: 'afterCursor',
      type: 'String',
    },
    {
      kind: 'RootArgument',
      name: 'count',
      type: 'Int',
    },
  ],
  kind: 'Fragment',
  metadata: {
    connection: [
      {
        count: 'count',
        cursor: 'afterCursor',
        direction: 'forward',
        path: ['user', 'posts'],
      },
    ],
  },
  name: 'UserPosts_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: null,
      args: null,
      concreteType: 'User',
      name: 'user',
      plural: false,
      selections: [
        {
          kind: 'LinkedField',
          alias: 'posts',
          args: null,
          concreteType: 'PostConnection',
          name: '__UserPosts_posts_connection',
          plural: false,
          selections: [
            {
              kind: 'LinkedField',
              alias: null,
              args: null,
              concreteType: 'PageInfo',
              name: 'pageInfo',
              plural: false,
              selections: [
                {
                  kind: 'ScalarField',
                  alias: null,
                  args: null,
                  name: 'hasNextPage',
                  storageKey: null,
                },
                {
                  kind: 'ScalarField',
                  alias: null,
                  args: null,
                  name: 'endCursor',
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              kind: 'LinkedField',
              alias: null,
              args: null,
              concreteType: 'PostEdge',
              name: 'edges',
              plural: true,
              selections: [
                {
                  kind: 'LinkedField',
                  alias: null,
                  args: null,
                  concreteType: 'Post',
                  name: 'node',
                  plural: false,
                  selections: [
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'id',
                      storageKey: null,
                    },
                    {
                      kind: 'FragmentSpread',
                      name: 'PostListItem_post',
                      args: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
      ],
      storageKey: null,
    },
  ],
  type: 'Viewer',
};

module.exports = fragment;
