/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Navigation_user.graphql
 * @generated SignedSource<<68472996127465343b5da8249d2a0767>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Navigation_user = {|
  +firstName: ?string;
  +role: ?string;
  +postCount: ?number;
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [],
  kind: 'Fragment',
  metadata: null,
  name: 'Navigation_user',
  selections: [
    {
      kind: 'ScalarField',
      alias: null,
      args: null,
      name: 'firstName',
      storageKey: null,
    },
    {
      kind: 'ScalarField',
      alias: null,
      args: null,
      name: 'role',
      storageKey: null,
    },
    {
      kind: 'ScalarField',
      alias: null,
      args: null,
      name: 'postCount',
      storageKey: null,
    },
  ],
  type: 'User',
};

module.exports = fragment;
