/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule App_viewer.graphql
 * @generated SignedSource<<2603e09b2cd894e93a93ad64b865cf03>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type App_viewer = {|
  +user: ?{| |};
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [],
  kind: 'Fragment',
  metadata: null,
  name: 'App_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: null,
      args: null,
      concreteType: 'User',
      name: 'user',
      plural: false,
      selections: [
        {
          kind: 'FragmentSpread',
          name: 'Header_user',
          args: null,
        },
        {
          kind: 'FragmentSpread',
          name: 'Navigation_user',
          args: null,
        },
      ],
      storageKey: null,
    },
  ],
  type: 'Viewer',
};

module.exports = fragment;
