/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Routes_Register_Query.graphql
 * @generated SignedSource<<b5e2a9789f3445c278df46380661174c>>
 * @relayHash 54e9dc7bc05b734f33a593f2565848a0
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/*
query Routes_Register_Query {
  viewer {
    ...Register_viewer
  }
}

fragment Register_viewer on Viewer {
  user {
    id
    role
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'Routes_Register_Query',
    selections: [
      {
        kind: 'LinkedField',
        alias: 'viewer',
        args: null,
        concreteType: 'Viewer',
        name: '__viewer_viewer',
        plural: false,
        selections: [
          {
            kind: 'FragmentSpread',
            name: 'Register_viewer',
            args: null,
          },
        ],
        storageKey: null,
      },
    ],
    type: 'Root',
  },
  id: null,
  kind: 'Batch',
  metadata: {},
  name: 'Routes_Register_Query',
  query: {
    argumentDefinitions: [],
    kind: 'Root',
    name: 'Routes_Register_Query',
    operation: 'query',
    selections: [
      {
        kind: 'LinkedField',
        alias: null,
        args: null,
        concreteType: 'Viewer',
        name: 'viewer',
        plural: false,
        selections: [
          {
            kind: 'LinkedField',
            alias: null,
            args: null,
            concreteType: 'User',
            name: 'user',
            plural: false,
            selections: [
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'id',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'role',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        storageKey: null,
      },
      {
        kind: 'LinkedHandle',
        alias: null,
        args: null,
        handle: 'viewer',
        name: 'viewer',
        key: '',
        filters: null,
      },
    ],
  },
  text: 'query Routes_Register_Query {\n  viewer {\n    ...Register_viewer\n  }\n}\n\nfragment Register_viewer on Viewer {\n  user {\n    id\n    role\n  }\n}\n',
};

module.exports = batch;
