/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Routes_App_Query.graphql
 * @generated SignedSource<<e0f2fd8b8dacd0d00981369a59b780ce>>
 * @relayHash 9660e5e870fed43bc348e813c7ba94b8
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/*
query Routes_App_Query {
  viewer {
    ...App_viewer
  }
}

fragment App_viewer on Viewer {
  user {
    ...Header_user
    ...Navigation_user
    id
  }
}

fragment Header_user on User {
  firstName
  lastName
  role
  postCount
}

fragment Navigation_user on User {
  firstName
  role
  postCount
}
*/

const batch /*: ConcreteBatch*/ = {
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'Routes_App_Query',
    selections: [
      {
        kind: 'LinkedField',
        alias: 'viewer',
        args: null,
        concreteType: 'Viewer',
        name: '__viewer_viewer',
        plural: false,
        selections: [
          {
            kind: 'FragmentSpread',
            name: 'App_viewer',
            args: null,
          },
        ],
        storageKey: null,
      },
    ],
    type: 'Root',
  },
  id: null,
  kind: 'Batch',
  metadata: {},
  name: 'Routes_App_Query',
  query: {
    argumentDefinitions: [],
    kind: 'Root',
    name: 'Routes_App_Query',
    operation: 'query',
    selections: [
      {
        kind: 'LinkedField',
        alias: null,
        args: null,
        concreteType: 'Viewer',
        name: 'viewer',
        plural: false,
        selections: [
          {
            kind: 'LinkedField',
            alias: null,
            args: null,
            concreteType: 'User',
            name: 'user',
            plural: false,
            selections: [
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'firstName',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'lastName',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'role',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'postCount',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'id',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        storageKey: null,
      },
      {
        kind: 'LinkedHandle',
        alias: null,
        args: null,
        handle: 'viewer',
        name: 'viewer',
        key: '',
        filters: null,
      },
    ],
  },
  text: 'query Routes_App_Query {\n  viewer {\n    ...App_viewer\n  }\n}\n\nfragment App_viewer on Viewer {\n  user {\n    ...Header_user\n    ...Navigation_user\n    id\n  }\n}\n\nfragment Header_user on User {\n  firstName\n  lastName\n  role\n  postCount\n}\n\nfragment Navigation_user on User {\n  firstName\n  role\n  postCount\n}\n',
};

module.exports = batch;
