/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Routes_Home_Query.graphql
 * @generated SignedSource<<c4fef7029bd17cc9fae3158c8b4caae1>>
 * @relayHash 4723bdde2aa8086343d3d26eccd24219
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/*
query Routes_Home_Query {
  viewer {
    ...Home_viewer
  }
}

fragment Home_viewer on Viewer {
  user {
    role
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'Routes_Home_Query',
    selections: [
      {
        kind: 'LinkedField',
        alias: 'viewer',
        args: null,
        concreteType: 'Viewer',
        name: '__viewer_viewer',
        plural: false,
        selections: [
          {
            kind: 'FragmentSpread',
            name: 'Home_viewer',
            args: null,
          },
        ],
        storageKey: null,
      },
    ],
    type: 'Root',
  },
  id: null,
  kind: 'Batch',
  metadata: {},
  name: 'Routes_Home_Query',
  query: {
    argumentDefinitions: [],
    kind: 'Root',
    name: 'Routes_Home_Query',
    operation: 'query',
    selections: [
      {
        kind: 'LinkedField',
        alias: null,
        args: null,
        concreteType: 'Viewer',
        name: 'viewer',
        plural: false,
        selections: [
          {
            kind: 'LinkedField',
            alias: null,
            args: null,
            concreteType: 'User',
            name: 'user',
            plural: false,
            selections: [
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'role',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'id',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        storageKey: null,
      },
      {
        kind: 'LinkedHandle',
        alias: null,
        args: null,
        handle: 'viewer',
        name: 'viewer',
        key: '',
        filters: null,
      },
    ],
  },
  text: 'query Routes_Home_Query {\n  viewer {\n    ...Home_viewer\n  }\n}\n\nfragment Home_viewer on Viewer {\n  user {\n    role\n    id\n  }\n}\n',
};

module.exports = batch;
