/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Routes_Login_Query.graphql
 * @generated SignedSource<<eccc481f474352ff6e0bf195a1323add>>
 * @relayHash 6fed8091d5e59bf5e6710e1cf1270477
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/*
query Routes_Login_Query {
  viewer {
    ...Login_viewer
  }
}

fragment Login_viewer on Viewer {
  user {
    id
    role
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'Routes_Login_Query',
    selections: [
      {
        kind: 'LinkedField',
        alias: 'viewer',
        args: null,
        concreteType: 'Viewer',
        name: '__viewer_viewer',
        plural: false,
        selections: [
          {
            kind: 'FragmentSpread',
            name: 'Login_viewer',
            args: null,
          },
        ],
        storageKey: null,
      },
    ],
    type: 'Root',
  },
  id: null,
  kind: 'Batch',
  metadata: {},
  name: 'Routes_Login_Query',
  query: {
    argumentDefinitions: [],
    kind: 'Root',
    name: 'Routes_Login_Query',
    operation: 'query',
    selections: [
      {
        kind: 'LinkedField',
        alias: null,
        args: null,
        concreteType: 'Viewer',
        name: 'viewer',
        plural: false,
        selections: [
          {
            kind: 'LinkedField',
            alias: null,
            args: null,
            concreteType: 'User',
            name: 'user',
            plural: false,
            selections: [
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'id',
                storageKey: null,
              },
              {
                kind: 'ScalarField',
                alias: null,
                args: null,
                name: 'role',
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        storageKey: null,
      },
      {
        kind: 'LinkedHandle',
        alias: null,
        args: null,
        handle: 'viewer',
        name: 'viewer',
        key: '',
        filters: null,
      },
    ],
  },
  text: 'query Routes_Login_Query {\n  viewer {\n    ...Login_viewer\n  }\n}\n\nfragment Login_viewer on Viewer {\n  user {\n    id\n    role\n  }\n}\n',
};

module.exports = batch;
