/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PostDetail_viewer.graphql
 * @generated SignedSource<<80b2a0aeac0b767d340e4559e72b084f>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PostDetail_viewer = {|
  +post: ?{|
    +title: ?string;
    +description: ?string;
  |};
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [
    {
      kind: 'RootArgument',
      name: 'postId',
      type: 'String',
    },
  ],
  kind: 'Fragment',
  metadata: null,
  name: 'PostDetail_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: null,
      args: [
        {
          kind: 'Variable',
          name: 'postId',
          variableName: 'postId',
          type: 'String',
        },
      ],
      concreteType: 'Post',
      name: 'post',
      plural: false,
      selections: [
        {
          kind: 'ScalarField',
          alias: null,
          args: null,
          name: 'title',
          storageKey: null,
        },
        {
          kind: 'ScalarField',
          alias: null,
          args: null,
          name: 'description',
          storageKey: null,
        },
      ],
      storageKey: null,
    },
  ],
  type: 'Viewer',
};

module.exports = fragment;
