/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Posts_viewer.graphql
 * @generated SignedSource<<3eea0a83adc6e57afe4f7fff32939cca>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Posts_viewer = {|
  +posts: ?{|
    +pageInfo: {|
      +hasNextPage: boolean;
      +endCursor: ?string;
    |};
    +edges: ?$ReadOnlyArray<?{|
      +node: ?{|
        +id: string;
      |};
    |}>;
  |};
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [
    {
      kind: 'RootArgument',
      name: 'afterCursor',
      type: 'String',
    },
    {
      kind: 'RootArgument',
      name: 'count',
      type: 'Int',
    },
  ],
  kind: 'Fragment',
  metadata: {
    connection: [
      {
        count: 'count',
        cursor: 'afterCursor',
        direction: 'forward',
        path: ['posts'],
      },
    ],
  },
  name: 'Posts_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: 'posts',
      args: null,
      concreteType: 'PostConnection',
      name: '__Posts_posts_connection',
      plural: false,
      selections: [
        {
          kind: 'LinkedField',
          alias: null,
          args: null,
          concreteType: 'PageInfo',
          name: 'pageInfo',
          plural: false,
          selections: [
            {
              kind: 'ScalarField',
              alias: null,
              args: null,
              name: 'hasNextPage',
              storageKey: null,
            },
            {
              kind: 'ScalarField',
              alias: null,
              args: null,
              name: 'endCursor',
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        {
          kind: 'LinkedField',
          alias: null,
          args: null,
          concreteType: 'PostEdge',
          name: 'edges',
          plural: true,
          selections: [
            {
              kind: 'LinkedField',
              alias: null,
              args: null,
              concreteType: 'Post',
              name: 'node',
              plural: false,
              selections: [
                {
                  kind: 'ScalarField',
                  alias: null,
                  args: null,
                  name: 'id',
                  storageKey: null,
                },
                {
                  kind: 'FragmentSpread',
                  name: 'PostListItem_post',
                  args: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
      ],
      storageKey: null,
    },
  ],
  type: 'Viewer',
};

module.exports = fragment;
