/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Register_viewer.graphql
 * @generated SignedSource<<71073255c2a31cfc07fc1f5b655c3dfe>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Register_viewer = {|
  +user: ?{|
    +id: string;
    +role: ?string;
  |};
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [],
  kind: 'Fragment',
  metadata: null,
  name: 'Register_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: null,
      args: null,
      concreteType: 'User',
      name: 'user',
      plural: false,
      selections: [
        {
          kind: 'ScalarField',
          alias: null,
          args: null,
          name: 'id',
          storageKey: null,
        },
        {
          kind: 'ScalarField',
          alias: null,
          args: null,
          name: 'role',
          storageKey: null,
        },
      ],
      storageKey: null,
    },
  ],
  type: 'Viewer',
};

module.exports = fragment;
